# cpp-engine/Makefile

# Compiler to use
CXX = g++
# Compiler flags 
CXXFLAGS = -std=c++11 -Wall -I"cpp-engine/vcpkg/installed/x64-windows/include"
# Target executable
TARGET = engine

# Sources and object files
SRC = $(wildcard src/*.cpp)
OBJ = $(SRC:.cpp=.o)

# Default target
all: $(TARGET)

$(TARGET): $(OBJ)
    $(CXX) $(CXXFLAGS) -o $@ $^

clean:
    rm -f $(TARGET) $(OBJ)